### ISSUE TITLE
The example of DataSream connector api should change RocketMQSource to RocketMQSourceFunction in the document. 

### ISSUE THREAD

**Issue by mispower** [apache/rocketmq-flink#11]
The DataStream example need update. All parameters  of the source instance and the sink  instance are not math.
``` 
env.addSource(new _**RocketMQSource**_(new SimpleKeyValueDeserializationSchema("id", "address"), consumerProps))
            .name("rocketmq-source")
            .setParallelism(2)....
```

**Comment by SteNicholas** [comment]
@mispower , it's recommended to use the `RocketMQSource` for the new Source interace of Flink. Which RocketMQ source are you using?
