### ISSUE TITLE
'consumer.offset.reset.to' is not supported in sql api

### ISSUE THREAD

**Issue by liyubin117** [apache/rocketmq-flink#12]
as document figured, `consumer.offset.reset.to` can be used to identify initial offset,
in fact, throw exception as follow:

```
Unsupported options:
consumer.offset.reset.to
```

**Comment by SteNicholas** [comment]
@liyubin117, do you mean that the table opion of the RocketMQ source has no `consumer.offset.reset.to` opion?

**Comment by liyubin117** [comment]
> @liyubin117, do you mean that the table opion of the RocketMQ source has no `consumer.offset.reset.to` opion?

yes, very weird

**Comment by SteNicholas** [comment]
@liyubin117 , do you want to contribute this table option?

**Comment by GOODBOY008** [comment]
@SteNicholas I'm very interested in this,please assign the issue to me.

**Comment by liyubin117** [comment]
@SteNicholas sorry for the late reply, I will make a pull request. :)

**Comment by liyubin117** [comment]
@SteNicholas Hi, could you please give a review? Thanks :)
