### ISSUE TITLE
Can support AliCloud RocketMQ

### ISSUE THREAD

**Issue by yangmingjie** [apache/rocketmq-flink#15]
我们是用的flink sql 做数据开发， 期待大佬回复。

**Comment by duhenglucky** [comment]
可以的，配置一下aksk 就可以了

**Comment by kongslove** [comment]
@duhenglucky 是否支持flink1.12.x版本

**Comment by yangmingjie** [comment]
> 可以的，配置一下aksk 就可以了

![image](https://user-images.githubusercontent.com/5827183/139842280-3b887536-46e0-43cf-94cf-b71883633238.png)

**Comment by vongosling** [comment]
@duhenglucky @SteNicholas Do we provide config addresses in cloud products. IMO, It would be better to provide this info in the cloud product's wiki, not here.

**Comment by yangmingjie** [comment]
> @duhenglucky @SteNicholas Do we provide config addresses in cloud products. IMO, It would be better to provide this info in the cloud product's wiki, not here.

大神，我是用的flink sql 开发的就像上面的截图，这个怎么配置？

**Comment by lizhimins** [comment]
旧版本 org.apache.rocketmq.flink.legacy.example.RocketMQFlinkExample
新版本 org.apache.rocketmq.flink.source.RocketMQSource#createReader
