### ISSUE TITLE
Can't find constructor RocketMQSource(KeyValueDeserializationSchema<OUT> schema, Properties props)

### ISSUE THREAD

**Issue by dcy652701** [apache/rocketmq-flink#18]
The README guide told to use RocketMQSource(KeyValueDeserializationSchema<OUT> schema, Properties props) for creating a source.But I can't find the constructor which has these two params. I can run on my IDEA

**Comment by SteNicholas** [comment]
@dcy652701 , thanks for the reportor of the problem in README.md. The `RocketMQSource(KeyValueDeserializationSchema schema, Properties props)` should be `RocketMQSourceFunction(KeyValueDeserializationSchema schema, Properties props)`. Do you have interest to update this?

**Comment by hunter-cloud09** [comment]
You can give it to me if you want
