### ISSUE TITLE
How to create a flink  table(flink sql) link to aliyun RocketMQ sevice with AccessKey ID and  AccessKey Secret?

### ISSUE THREAD

**Issue by yangmingjie** [apache/rocketmq-flink#20]
![image](https://user-images.githubusercontent.com/5827183/140869629-8e131e13-9b24-4cfb-9328-ec08f711c4a5.png)

**Comment by yangmingjie** [comment]
The demand is urgent，thanks a lot

**Comment by SteNicholas** [comment]
@yangmingjie , current version doesn't support the ack. I'm adding the ack to the table option. If you are agent, please add the wechat: 834031959 to discuss.

**Comment by complone** [comment]
> @yangmingjie, 当前版本不支持 ack。我正在将 ack 添加到 table 选项。如果您是代理，请加微信：834031959进行讨论。

If you support it, I plan to implement an example based on APIs such as DynamicTableSourceFactory DynamicTableFactory TableScanSource: https://blog.csdn.net/u010034713/article/details/107837488

**Comment by lizhimins** [comment]
We only need add the aclhook of rocketmq when constructing the producer and consumer, then add the parameter configuration in the SQL

**Comment by GOODBOY008** [comment]
@SteNicholas I'm very interested in this,please assign the issue to me.

**Comment by GOODBOY008** [comment]
Hi @duhenglucky ,This issue had supported by pr https://github.com/apache/rocketmq-flink/pull/47 .
