### ISSUE TITLE
Can it support flink 1.12?

### ISSUE THREAD

**Issue by miaofu1997** [apache/rocketmq-flink#22]
I'm currently using flink 1.12, but the whole project is based on flink 1.13. 
I tried to make some modifications to accomodate my flink version, only to find that there are more differences to modify than i expected.
Need some help!

**Comment by yangmingjie** [comment]
https://github.com/apache/rocketmq-flink/issues/17

**Comment by SteNicholas** [comment]
@miaofu1997, the 1.12 version should be supported by yourselft. Because the `RocketMQSource` only supports the 1.13+ version of Flink, but the legacy `RocketMQSourceFunction` could support the 1.12.x version.
