### ISSUE TITLE
Implementation of Apache RocketMQ Flink Catalog 

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-flink#32]
题目名称：Apache RocketMQ Flink Catalog 实现
导师介绍：蒋晓峰，[@SteNicholas](https://github.com/SteNicholas), Apache RocketMQ & Kyuubi & ShardingSphere Committer。
导师邮箱：nicholasjiang@apache.org
题目难度：进阶
题目描述：支持 Apache RocketMQ Flink Catalog
1、学习Apache Flink Catalog 知识，详细了解 Flink RocketMQ Connector 原理、使用方式、参数含义等。
2、根据 Flink Catalog Public Interfaces 实现 RocketMQCatalog
3、在社区中提交 Issue，完成相关代码，review后被社区合并

**Comment by li-xiao-shuang** [comment]
I will solve it

**Comment by SteNicholas** [comment]
@li-xiao-shuang, thanks for your willing contribution for RocketMQ Catalog. Please go ahead to implement.

**Comment by ShannonDing** [comment]
link #3
