### ISSUE TITLE
Documentation does not match reality about RocketMQSink.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/rocketmq-flink#65]
Documentation does not match reality about RocketMQSink.
<img width="709" alt="企业微信截图_16657406898846" src="https://user-images.githubusercontent.com/13617900/195816700-16ef39b7-fc0b-4cf6-8eb6-db0ba76de278.png">

**Comment by deemogsw** [comment]
The constructor of RocketMQSink has been revised.Now user should transform data to `Message` before useing sink function,so it's no need to specify a schema

**Comment by GOODBOY008** [comment]
PR had merged https://github.com/apache/rocketmq-flink/commit/90b00be02dd019ffed48cbc35cd050b07c4a36ab .
