### ISSUE TITLE
convertToRowTypeInfo() should return field name

### ISSUE THREAD

**Issue by liyubin117** [apache/rocketmq-flink#7]
`RocketMQDynamicTableSink#convertToRowTypeInfo()`
now just return field type information, so we don`t have the neccessary information to serialize field name to body, or use real field name instead of f0/f1.. relying on the order of field to identify the key column

I have enhanced the function in our department

**Comment by duhenglucky** [comment]
@liyubin117 would you like to add your information to this [issue](https://github.com/apache/rocketmq-flink/issues/1)？

**Comment by liyubin117** [comment]
@duhenglucky my pleasure
