### ISSUE TITLE
【Bug】Source cannot consume new queues' messages when topic queue expanded

### ISSUE THREAD

**Issue by humkum** [apache/rocketmq-flink#95]
After topic expanded, Flink jobs cannot consume new queues。Because of follow reasons:
1. restoredOffsets doesn't have new queues' checkpoint
2. Flink job start with offset from restoredOffsets wouldn't initialize offset for new queues. And the consumer wouldn't pull messages from new queues because the offsetTable doesn't contain new queues.

![image](https://github.com/apache/rocketmq-flink/assets/50660789/9d157d07-a142-477f-ba08-15b526ffe6f0)

**Comment by lizhimins** [comment]
Good catch
